### ISSUE TITLE
开机异常现象咨询

### ISSUE THREAD

**Issue by ittat** [MutouRenMe/Hackintosh-Clover-SurfacePro3#3]
你好，我的pro3 在黑苹果开机过程中会不断重启，偶尔运气好的时候才可以一次性进入系统。我改用你的EFI问题依旧，请问你在使用过程中有出现我这种情况吗？

**Comment by MutouRenMe** [comment]
我没有出现这种情况，只是极小概率会一次进不到系统，第二次就进了

**Comment by Suo-Ran** [comment]
很遗憾，我的也是，即使拿到了整个EFI分区下的文件，还是会异常重启，并且没有成功进去过

**Comment by MutouRenMe** [comment]
> 你好，我的pro3 在黑苹果开机过程中会不断重启，偶尔运气好的时候才可以一次性进入系统。我改用你的EFI问题依旧，请问你在使用过程中有出现我这种情况吗？



> 很遗憾，我的也是，即使拿到了整个EFI分区下的文件，还是会异常重启，并且没有成功进去过

抱歉这个问题我也不能解决，可能是因为我的EFI是我修改了一些东西，可以尝试用原作者的[EFI](https://github.com/hacker1024/Hackintosh-Clover-SurfacePro3)安装好，然后把我的EFI里的kext文件加进去，除了网卡驱动外好像只添加了两个kext

**Comment by ittat** [comment]
知道原因了，是我的VoodooI2C问题
